name: terraform-eu-dev

on: [push, pull_request]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
    
      - name: Terraform init
        id: init
        run: cd EU-DEV && terraform init

      - name: Terraform validate
        id: validate
        run:  cd EU-DEV && terraform validate

      - name: Terraform plan
        id: plan
        run: cd EU-DEV && terraform plan

      - name: Terraform apply
        id: apply
        run: cd EU-DEV && terraform apply -auto-approve