name: terraform-eu-dev

on: [push, pull_request]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
    
      - name: Terraform init
        id: init
        run: terraform init
        working-directory: EU-DEV

      - name: Terraform validate
        id: validate
        run:  terraform validate
        working-directory: EU-DEV

      - name: Terraform plan
        id: plan
        run: terraform plan
        working-directory: EU-DEV

      # - name: Terraform apply
      #   id: apply
      #   run: terraform apply -auto-approve
      #   working-directory: EU-DEV